$(function(){
  $("button").click(function(){
    $("div").each(function(){
      if($(this).css("display")=="none"){
        $(this).css("display","");
        console.log($(this).html()+$(this).css("color"));
      }
    });
  });
});
